//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examination_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SETEXAME
    {
        public int EXAME_ID { get; set; }
        public Nullable<System.DateTime> EXAME_DATE { get; set; }
        public Nullable<int> EXAME_FK_STU { get; set; }
        public string EXAME_NAME { get; set; }
        public Nullable<int> EXAME_STD_SCORE { get; set; }
    
        public virtual TBL_STUDENT TBL_STUDENT { get; set; }
    }
}
